
kind: Service
apiVersion: v1
metadata:
  name: "web-service"
  labels:
    app: website
spec:
  selector:
    app: python
  ports:
    - protocol: "TCP"
      port: 1377
      targetPort: 80
  type: LoadBalancer