
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: akshayttt/k8s-python:16
        ports:
        - containerPort: 80